### PR TITLE
Updated unsubscribe part

### PR DESCRIPTION
**Pull request by wonsuk73**
- Separated unsubscribe and unsubscribeAll in the section
- Replaced WebIDL with table

### CODE REVIEW

**Comment by wonsuk73** [comment]
@acrofts84 To handle optional property, subscriptionId, in unsubscribe messaging format, there was consensus to separate unsubscribe and unsubscribeAll as a separate section in the last Burmingham F2F meeting. Right? Could you review this?

**Comment by acrofts84** [comment]
Hi @wonsuk73,
Thank you for this. Sorry for the delay in my feedback, I have been on holiday and then had the post-holiday catch up!

I've had a read through and it looks good. There are a couple of minor modifications I have done:
- Added links to the table at the top of the Message Structure section to include unsubscribeAll request
- A couple of text mistakes have been corrected in the JSON schema descriptions
- Made the headings consistent with use of capitalisation

Happy to merge, if you are happy with my new commit.

Thanks, 

Adam

**Comment by wonsuk73** [comment]
@acrofts84, I hope you had great time in holidays! :-) 
Thanks for modification! Looks good to me!

**Comment by acrofts84** [comment]
Thanks Wonsuk :)

**Pull request merged**
