### PR TITLE
start of a privacy section

### LINKED ISSUE #373: Application opt in/out
On our last group call @PeterWinzell requested an estimated timeline to publish VISS version 2. @UlfBj and I agree we need to have a privacy section, perhaps containing some ideas that came out of the related issue from our charter review. 

https://www.w3.org/2021/03/09-auto-minutes.html (also contains minutes from earlier VSSo call)

https://github.com/w3c/automotive/issues/358

We also are working towards an early draft release of In-Vehicle Application Best Practices and referring to it for privacy, security and other considerations beyond the scope of the spec. Glenn pushed us to explore trying to tackle the problem with a technical solution, something I and others have felt daunting managing consent, policies, parties and purposes globally across legal jurisdictions with differing and evolving privacy laws. Further complicated with out of band consent in form of eg contractual obligations for operating a fleet vehicle. @adobekan wanted us to consider more fundamental approach. 

Continued thinking about some ideas on the call surrounding the authentication and authorization mechanisms of VISS. @UlfBj and I chatted, he had some thoughts about how we may have some capability with the current design. Based on previous best practices and RPC discussions I think there are a few parameters that could influence whether an application is allowed to access data for a given drive. The directive with these parameters could originate on the head unit, smart phone or by OEM or other application manager from the cloud.

Parameters on whether an installed application can collect data can be based on a routine schedule (off work hours), specific opt-in/out period likely following a specific driver's preference or rental agreement,  geofencing, or blanket binary on or off changing the default policy for an application. Some applications, for instance collecting data for regulators on heavy vehicles in EU and NA, may not be permitted to set some parameters. More complex scenarios using wider range of inputs can be managed by logic in the cloud and still keep the number of parameters needed to relay to auth* servers modest.

We will likely progress VISS v2 to First Public Working Draft without completing this but can add in a later version as the ideas get flushed out a bit more.

### PR DESCRIPTION
**Pull request by tguild**
@UlfBj and others, please take a read of my start of a privacy section for VISSv2

Input welcome

### CODE REVIEW

**Comment by UlfBj** [comment]
>>All information sent from a VISS service to client application must be encrypted.

This could be interpreted as that encryption must be applied to the data independently of the confidentiality protection given by the transport protocol, which I think should not be a requirement. 
With that view I would rewrite it as shown below.

All information sent from a VISS service to client application must be transported over a confidentiality protected protocol.

**Comment by tguild** [comment]
Hej @UlfBj how about:

All information sent from a VISS service to client application must be transported over an encrypted protocol to help protect privacy.

**Comment by UlfBj** [comment]
>> All information sent from a VISS service to client application must be transported over an encrypted protocol to help protect privacy.

It makes it clear, so it is fine from my point of view.

**Comment by tguild** [comment]
Don't merge yet, additional changes from #378 and today's call

**Comment by tguild** [comment]
@peterMelco let me know if you have better wording for what you raised in 

https://github.com/w3c/automotive/issues/378

**Review by UlfBj — APPROVED** [review]

**Pull request merged**
