### PR TITLE
Proposed texts for initialization, closure of HTTPS and merged signal discovery read with dynamic metadata read on HTTPS parts

### PR DESCRIPTION
**Pull request by wonsuk73**
1) This is the draft texts for initialization and closure of session life time management on HTTPS transport protocol
2) I might need to merge signal discovery read with dynamic metadata read on HTTPS parts. Because it need to make the sync with WebSocket part. In addition Signal discovery read can use the both static metadata and dynamic metadata on the request message.

### CODE REVIEW

**Comment by tguild** [comment]
Hi @wonsuk73 ,

@UlfBj and I read through your PR and it makes sense with the exception of the sentence about hostname generally having www prefix as that will not be the case when VISS is on a local, in-vehicle network and unlikely as well if remote vehicle connections are allowed.

**Comment by wonsuk73** [comment]
@tguild and @UlfBj Thanks for valuable comment! I revised texts. Could you review on this? In addition if you have any ideas to enhance the description, please let me know!

**Comment by wonsuk73** [comment]
@tguild, @UlfBj, could you review on revised one?

**Comment by UlfBj** [comment]
@wonsuk73,
The sentence:
A client may send a signal discovery read request to access dynamic metadata. 
is in conflict with what is said in the static metadata chapter
https://raw.githack.com/w3c/automotive/gh-pages/spec/VISSv2_Core.html#static-metadata-request
where the term "signal discovery is bound to that type of request.
I propose that this sentence is removed from the PR.
The initialsization/closure parts look fine to me.

**Comment by wonsuk73** [comment]
@UlfBj Thanks for review! I fixed the conflict sentence you mentioned :)

**Pull request merged**
