### PR TITLE
removal of etc from spec

### PR DESCRIPTION
**Pull request by MelcoGot**
Please review the removal of etc from spec. Beware of limitations that these changes could indicate.

### CODE REVIEW

**Comment by acrofts84** [comment]
I don't believe this has introduced any limitations because there is always a word/phrase which states that the list is not exhaustive ('including', 'e.g' or 'such as'). I also agree that it reads better as a result of this change.

I have a couple of comments for readability, but that is it. Changing this:
<pre>Driver able to see fuel such as economy, consumption, level and range.</pre>
With
<pre>Driver able to see fuel status such as economy, consumption, level and range.</pre>

And this (I realise this isn't anything to do with your proposed change):
<pre>and is given an snapshot</pre>
With:
<pre>and is given a snapshot</pre>

**Comment by wonsuk73** [comment]
@MelcoGot, could you update your pull request to have comments from @acrofts84 ?

**Comment by peterMelco** [comment]
Since I don't have write access - how to do with the comments from acrotft ?

**Comment by wonsuk73** [comment]
@peterMelco you are different guy with @MelcoGot. Right? just checking! :)  Can I ask which write access do you mean?

**Comment by wonsuk73** [comment]
This pull request made conflict to be merged. So it has been done via Pull request #57 and #58

**Comment by peterMelco** [comment]
Hi !
Not sure…I am probably both…
/pw

**Pull request closed without merging**
