### PR TITLE
Clarify the getVSS method

### PR DESCRIPTION
**Pull request by acrofts84**
Introduce a data structure in the example and add further explanation

### CODE REVIEW

**Comment by rstreif** [comment]
This looks good to me and reflects the full VSS. It's ok to be merged from my side. I still would like to entertain the idea raised in #133 adding a parameter to getVSS to specify either this verbose format or a more compact format. But that can be another PR.

**Comment by aShinjiroUrata** [comment]
Hi @acrofts84 , thank you very much for the update!
Just for minor point, I suppose the request path should be "Signal.Drivetrain.InternalCombustionEngine.RPM" than "Signal.Body" in this case, isn't it?

Except for this point, the change looks fine to me.

**Comment by aShinjiroUrata** [comment]
Hi @acrofts84 , thank you for the fix!
This PR is OK to me.

**Comment by acrofts84** [comment]
Thank you both. I've updated the request path. I'll add to the discussion regarding the verbose mode in issue #132.

**Comment by wonsuk73** [comment]
@acrofts84 @rstreif @aShinjiroUrata Thanks for contributions. It looks good to me as well. So it just  merged.

**Pull request merged**
