### PR TITLE
Update data_spec.html

### PR DESCRIPTION
**Pull request by gbrannonaaa**
To address issue #32

### CODE REVIEW

**Comment by wonsuk73** [comment]
@gbrannonaaa, TroubleCodeType have three types like current, pending and history in the proposal. What does 'pending' type mean?

**Comment by gbrannonaaa** [comment]
It is one on three defined types of codes by SAE standard.  OEMs will have no issues understanding the meaning.

**Comment by wonsuk73** [comment]
@gbrannonaaa, I understood which types are from. By the way I am still curious about meaning of type 'pending' ;)

**Comment by gbrannonaaa** [comment]
OBD II Pending Codes are also referred to as “continuous monitor” and “maturing codes”. An intermittent fault will cause the computer to store a pending code in memory. If the fault does not recur within a certain number of cycles, the code will be cleared from memory. If the fault recurs a specific number of times, the code will then mature into a diagnostic trouble code (DTC).

**Pull request merged**
