### PR TITLE
[data-spec] Adding parking sensors interface

### PR DESCRIPTION
**Pull request by acrofts84**
An interface to return the distance to the nearest object using the parking sensors. Provides a distance attribute, an active attribute and a zone attribute.

<pre> <code>
active of type boolean, readonly , nullable
must return true if parking sensors are currently in use
distanceToObject of type short, readonly , nullable
must return the approximate distance to the nearest object from the parking sensor. If no objects are sensed this should return null (Unit: millimeters)
zone of type Zone, readonly , nullable
must return Zone for requested attribute
</code></pre>

### CODE REVIEW

**Comment by wonsuk73** [comment]
@acrofts84, Recently new car has a lot of parking sensors in back and front sides as well. Could your proposal can cover all of sensors where are back and front in any density?

**Comment by wonsuk73** [comment]
@aShinjiroUrata @QingAn Do you have any comment on this PR?

**Comment by aShinjiroUrata** [comment]
Hi! basically this is OK to me.

This sensor is used only at parking time?
If sensor information can be used while car is running,
 then names like `distanceSensors`, `proximitySensors` would be other option.

Bt the way,
>@acrofts84, Recently new car has a lot of parking sensors in back and front sides as well. Could >your proposal cover all of sensors where are back and front in any density?

as personal opinion, OEM can put as many sensors as they like and I think it is not possible to 
 cover such various sensors of various models of cars by current `Zone` method. 
But I think, it is not this `parkingSensors` interface's problem but `Zone` system's limitation.

**Comment by wonsuk73** [comment]
@aShinjiroUrata, Thanks for comments!
@acrofts84 I will merge your proposal to the spec with editor note for indicating that it might need to revisit the name of 'parkingSensors'. And this PR also has a conflict. So I will make an alternative PR with  editor's note.

**Comment by wonsuk73** [comment]
This PR has been replaced with PR #70 because of conflict.

**Comment by acrofts84** [comment]
Thanks @wonsuk73 @aShinjiroUrata.

**Pull request closed without merging**
