### PR TITLE
Add JSON Schema Definitions to Each Interface

### PR DESCRIPTION
**Pull request by acrofts84**
Added a heading to each section showing the existing Web IDL, followed by a heading for JSON Schema and the equivalent JSON Schema

### CODE REVIEW

**Comment by acrofts84** [comment]
Thank you both, I have integrated your recommendations.

**Comment by rstreif** [comment]
Thank you @acrofts84. I am ok with merging.

**Comment by wonsuk73** [comment]
@acrofts84 Sorry for late reply because I had a little big long vacation :-)
Can I ask why doesn't remove the WebIDL definition? If it is to check the matches in detail during migration from WebIDL to JSON schema, that is okay. But...

If there are two definitions for VISS. I think it could make a confusion for the readers because WebIDL and JSON schema use different data types like DOMString, DOMTimeStamp and Any. So my proposal is only to use JSON schema for VISS in this spec.

**Comment by acrofts84** [comment]
@wonsuk73, no problem. I hope you enjoyed it :).

The reason to keep the WebIDL is it is more human readable.  I agree that the data types may lead to confusion. I can see the argument for both keeping and removing the WebIDL, so was planning to raise this issue and hopefully come to a consensus in the call on 21st Feb.

**Comment by PeterWinzell** [comment]
I think we also had an argument that if someone would like to have a browser implementation of the spec it would be helpful with WebIDL defintions. I agree with @wonsuk73  that it could and mayabe actually should  be removed.

**Comment by wonsuk73** [comment]
@acrofts84 @peterMelco As you know in case of WebIDL that is typically used for javascript API which is primitively supported by the browser. It is not appropriate for server side APIs like VISS. It should be used our client spec. What do you think?

**Comment by peterMelco** [comment]
@wonsuk73  I completely agree with you.

**Comment by acrofts84** [comment]
As discussed over email, I think the best way forward is to merge this request and the removal/replacement of Web IDL can be the subject of a future pull request.

**Pull request merged**
